local colors = require("themes." .. _G.theme)

require("mini.base16").setup({
    palette = colors,
})

local function hi(group, args)
    local cmd = string.format(
        "highlight %s guifg=%s guibg=%s gui=%s",
        group,
        args.fg or "NONE",
        args.bg or "NONE",
        args.gui or "NONE"
    )
    vim.cmd(cmd)
end

local function hi_link(group, link)
    local cmd = string.format("highlight! link %s %s", group, link)
    vim.cmd(cmd)
end

hi("WinSeparator", { fg = colors.base02 })
hi("NormalFloat", { fg = colors.base05, bg = colors.base00 })
hi("FloatBorder", { fg = colors.base05, bg = colors.base00 })
hi("LineNr", { fg = colors.base03 })
hi("SignColumn", { fg = colors.base03 })

hi("DiagnosticFloatingError", { fg = colors.base08, bg = colors.base00 })
hi("DiagnosticFloatingHint", { fg = colors.base0A, bg = colors.base00 })
hi("DiagnosticFloatingInfo", { fg = colors.base0C, bg = colors.base00 })
hi("DiagnosticFloatingOk", { fg = colors.base0B, bg = colors.base00 })
hi("DiagnosticFloatingWarn", { fg = colors.base0E, bg = colors.base00 })
hi("DiagnosticSignError", { fg = colors.base08, bg = colors.base00 })
hi("DiagnosticSignHint", { fg = colors.base0A, bg = colors.base00 })
hi("DiagnosticSignInfo", { fg = colors.base0C, bg = colors.base00 })
hi("DiagnosticSignOk", { fg = colors.base0B, bg = colors.base00 })
hi("DiagnosticSignWarn", { fg = colors.base0E, bg = colors.base00 })

hi("MiniFilesBorder", { fg = colors.base05 })
hi("MiniFilesCursorLine", { bg = colors.base01 })
hi("MiniFilesTitle", { bg = colors.base00 })
hi("MiniFilesTitleFocused", { bg = colors.base00 })
hi("MiniFilesBorderModified", { fg = colors.base0A })
hi("MiniStarterItemPrefix", { fg = colors.base0D })
hi("MiniFilesNormal", { fg = colors.base05, bg = colors.base00 })

hi("BlinkCmpMenu", { fg = colors.base05, bg = colors.base00 })
hi("BlinkCmpMenuBorder", { fg = colors.base05, bg = colors.base00 })
hi("BlinkCmpMenuSelection", { fg = colors.base05, bg = colors.base01 })
hi("BlinkCmpKind", { bg = colors.base00 })

-- Credits to NvChad
hi("DevIconc", { fg = colors.base0D })
hi("DevIconcss", { fg = colors.base0D })
hi("DevIcondeb", { fg = colors.base0C })
hi("DevIconDockerfile", { fg = colors.base0C })
hi("DevIconhtml", { fg = colors.base09})
hi("DevIconjpeg", { fg = colors.base0E })
hi("DevIconjpg", { fg = colors.base0E })
hi("DevIconjs", { fg = colors.base0A })
hi("DevIconkt", { fg = colors.base09 })
hi("DevIconlock", { fg = colors.base08 })
hi("DevIconlua", { fg = colors.base0D })
hi("DevIconmp3", { fg = colors.base05 })
hi("DevIconmp4", { fg = colors.base05 })
hi("DevIconout", { fg = colors.base05 })
hi("DevIconpng", { fg = colors.base0E })
hi("DevIconpy", { fg = colors.base0C })
hi("DevIcontoml", { fg = colors.base0D })
hi("DevIconts", { fg = colors.base0D})
hi("DevIconttf", { fg = colors.base05 })
hi("DevIconrb", { fg = colors.base08})
hi("DevIconrpm", { fg = colors.base09 })
hi("DevIconvue", { fg = colors.base0B})
hi("DevIconwoff", { fg = colors.base05 })
hi("DevIconwoff2", { fg = colors.base05 })
hi("DevIconxz", { fg = colors.base0A })
hi("DevIconzip", { fg = colors.base0A })
hi("DevIconZig", { fg = colors.base09 })
hi("DevIconMd", { fg = colors.base0D })
hi("DevIconTSX", { fg = colors.base0D })
hi("DevIconJSX", { fg = colors.base0D })
hi("DevIconSvelte", { fg = colors.base08 })
hi("DevIconJava", { fg = colors.base09 })
hi("DevIconDart", { fg = colors.base0C })
hi("DevIconNix", { fg = colors.base0C })
hi("DevIconNixOS", { fg = colors.base0C })

hi_link("BlinkCmpKindClass", "Type")
hi_link("BlinkCmpKindColor", "Special")
hi_link("BlinkCmpKindConstant", "Constant")
hi_link("BlinkCmpKindConstructor", "Type")
hi_link("BlinkCmpKindEnum", "Structure")
hi_link("BlinkCmpKindEnumMember", "Structure")
hi_link("BlinkCmpKindEvent", "Exception")
hi_link("BlinkCmpKindField", "Structure")
hi_link("BlinkCmpKindFile", "Tag")
hi_link("BlinkCmpKindFolder", "Directory")
hi_link("BlinkCmpKindFunction", "Function")
hi_link("BlinkCmpKindInterface", "Structure")
hi_link("BlinkCmpKindKeyword", "Keyword")
hi_link("BlinkCmpKindMethod", "Function")
hi_link("BlinkCmpKindModule", "Structure")
hi_link("BlinkCmpKindOperator", "Operator")
hi_link("BlinkCmpKindProperty", "Structure")
hi_link("BlinkCmpKindReference", "Tag")
hi_link("BlinkCmpKindSnippet", "Special")
hi_link("BlinkCmpKindStruct", "Structure")
hi_link("BlinkCmpKindText", "Statement")
hi_link("BlinkCmpKindTypeParameter", "Type")
hi_link("BlinkCmpKindUnit", "Special")
hi_link("BlinkCmpKindValue", "Identifier")
hi_link("BlinkCmpKindVariable", "Delimiter")
